### ISSUE TITLE
4.1.0 Not working on Apple TV

### ISSUE THREAD

**Issue by diemenz** [123Venom/plugin.video.venom#75]
I noticed this same issue on Fen when the new service settings management system was added into that add on. It would appear that system is not compatible with the way TVos manages the cache. I have tried multiple times to pull a log from the apple TV but I can't seem to pull it. I reverted back to 4.0.8 and it is still working with the old service settings management.

**Comment by 123Venom** [comment]
The settings changes in v4.1 is just window properties, which has been used for many other items throughout the addon before so I tend to doubt it's that doing it to you.  Unfortunately I have no access to apple TV to test.  I'm suspicious it's more in the comparability with the `reuselanguageinvoker` that it's on by default in v4.1 but off in prior versions.  Try turning that off...it's on the debug setting page and make sure to restart kodi.  Report back.  It would also be helpful to have a debug log.

**Comment by diemenz** [comment]
Unfortunately I cannot get the add on to open so I can't get into tools. I went back to the previous version and everything is working :)

**Comment by drinfernoo** [comment]
@diemenz Open the Settings dialog from the context menu or information window.

**Comment by rs84y75f83** [comment]
It’s not just 4.1.0 - the latest 4.1.2 has an issue too. 

I have also been receiving an error upon startup. 

I also receive an error trying to switch off the `reuseLanguageInvoker` in the developer debug menu. 

See my error log: https://paste.kodi.tv/emipacikod

**Comment by 123Venom** [comment]
>>It’s not just 4.1.0 - the latest 4.1.2 has an issue too.

Course it is cause I've not undone anything that lead to your issue.

How good are you with editing files?
Looks like I missed changing something.

[control.py - L129](https://github.com/123Venom/plugin.video.venom/blob/880b75f0ecaf4c22222b45d179d22e003bb89133/resources/lib/modules/control.py#L129)


Make that line look like so.  If you can do that post up another log.  You last log pointed me right to that line and I saw the error.
```
# profile_dir = xbmc.translatePath('special://userdata/addon_data/plugin.video.venom')
profile_dir = xbmc.translatePath('special://profile/addon_data/plugin.video.venom/')

**Comment by rs84y75f83** [comment]
@123Venom I've already looked through the source to that specific file, just didn't know what precisely to change it to.

No issue editing or even submitting a PR, just not sure how to get the changes onto an Apple TV given there's no external file system access. Might be best for it to be included on the next release you make

**Comment by rs84y75f83** [comment]
@123Venom Incidentally, I'd already had a little browse of the source directly to that file/line when I uploaded the log file, just didn't know what precisely to change it to as I'm not familiar with the inner workings.

No issue editing the source, just not sure how to get the changes onto an Apple TV given there's no external file system access. Might be best for it to be included on the next release you make

**Comment by 123Venom** [comment]
I uploaded a test version for you, v4.1.2a with that little fix.  Install and run that and post a new log and lets see what we look like now.

[Here](https://github.com/123Venom/zips/tree/dev)

**Comment by rs84y75f83** [comment]
> I uploaded a test version for you, v4.1.2a with that little fix. Install and run that and post a new log and lets see what we look like now.
> 
> [Here](https://github.com/123Venom/zips/tree/dev)

Thank you, I’m eager to test but have been unable to find a way to install this zip on the Apple TV as the file system cannot be externally accessed unlike on other clients. 

Perhaps you know of a way, as the only way I know is to install via a repository (that was installed from a zip).

**Comment by diemenz** [comment]
If you have a SMB share you can save the zip on the network computer and do an install from zip (like how you install a repo) I would test this but I am travelling for 10 days and don't have access to an Apple TV.

**Comment by 123Venom** [comment]
> 
> 
> > I uploaded a test version for you, v4.1.2a with that little fix. Install and run that and post a new log and lets see what we look like now.
> > [Here](https://github.com/123Venom/zips/tree/dev)
> 
> Thank you, I’m eager to test but have been unable to find a way to install this zip on the Apple TV as the file system cannot be externally accessed unlike on other clients.
> 
> Perhaps you know of a way, as the only way I know is to install via a repository (that was installed from a zip).

I pushed v4.1.3 that includes this path fix so if you could check again and post a log once installed.

**Comment by rs84y75f83** [comment]
@123Venom thank you for letting me know. I just installed 4.1.3 and receive some different errors now. 

New log: https://paste.kodi.tv/imiyonobag

**Comment by kasekesy** [comment]
im having same issue getting venom error see log, i was on 4.1.2 did a fresh reinstall of kodi and venom and now am on 4.1.3 and same issue wont open

**Comment by iAYMANi** [comment]
> > > I uploaded a test version for you, v4.1.2a with that little fix. Install and run that and post a new log and lets see what we look like now.
> > > [Here](https://github.com/123Venom/zips/tree/dev)
> > 
> > 
> > Thank you, I’m eager to test but have been unable to find a way to install this zip on the Apple TV as the file system cannot be externally accessed unlike on other clients.
> > Perhaps you know of a way, as the only way I know is to install via a repository (that was installed from a zip).
> 
> I pushed v4.1.3 that includes this path fix so if you could check again and post a log once installed.

FYI
Apple TV KODI V. 17.6 ONLY

**Comment by kasekesy** [comment]
> > > > I uploaded a test version for you, v4.1.2a with that little fix. Install and run that and post a new log and lets see what we look like now.
> > > > [Here](https://github.com/123Venom/zips/tree/dev)
> > > 
> > > 
> > > Thank you, I’m eager to test but have been unable to find a way to install this zip on the Apple TV as the file system cannot be externally accessed unlike on other clients.
> > > Perhaps you know of a way, as the only way I know is to install via a repository (that was installed from a zip).
> > 
> > 
> > I pushed v4.1.3 that includes this path fix so if you could check again and post a log once installed.
> 
> FYI
> Apple TV KODI V. 17.6 ONLY

I’m running kodi 17.6 and venom 4.1.3 and still getting rror

**Comment by 123Venom** [comment]
> 
> 
> @123Venom thank you for letting me know. I just installed 4.1.3 and receive some different errors now.
> 
> New log: https://paste.kodi.tv/imiyonobag

Looking over the new log this is what I'm seeing
Line 5732: `/userdata/addon_data/plugin.video.venom/ : already exists`
Line 5733:  `/userdata/addon_data/plugin.video.venom/settings.xml : already exists`
   That's perfect and kodi now sees the folder and file just fine with the path fix I did.
Line 5734: Clamis to fail right at line 131 in my control module.  That line in my code calls ElementTree to parse the settings.xml file the previous line says it exists. So the claim it does not exist is BS because previous line found it fine.  This tells me ElementTree is having the problem seeing this path and then reports it does not exist, when we know it does.  Is that installed on a compressed drive?  Unfortunately if Apple and ElemenTree do not get along I'm not undoing all my work to find this out now but that is what it looks like to me.  I've been in contact with the FEN dev and going to reasearch `xmltodict` function as a replacement to `ElementTree` to parse that settings.xml file and see if they get along...if not I'm afraid that's the end of the line for me.

**Comment by diemenz** [comment]
Version 4.0.8 had the same settings error but the addon would operate as normal. I have tried relentlessly to get any update past 4.1 to work on the Apple TV and cannot. Even on a fresh install of Kodi it crashes.

**Comment by 123Venom** [comment]
> 
> 
> Version 4.0.8 had the same settings error but the addon would operate as normal. I have tried relentlessly to get any update including and past 4.1 to work on the Apple TV and cannot. Even on a fresh install of Kodi it crashes.

That's because the path error I just fixed still exists in v4.0.8 but in a service that's not destructive to the addon running if it fails....that's why the log error there.  If I add that fix to 4.0.8 that log error would go away.  This new version uses a whole new method to access the settings and ElementTree is what's now failing on Apple TV.  Without access to that file the addon is dead in the water.

**Comment by kasekesy** [comment]
Does that mean it can’t be fixed? How do we install an older working version?

**Comment by 123Venom** [comment]
> 
> 
> Does that mean it can’t be fixed? How do we install an older working version?

We're going to look at a couple of options soon.  Sorry just tied up in another project right now.

**Comment by diemenz** [comment]
> Does that mean it can’t be fixed? How do we install an older working version?

Unless you actively delete your kodi files there will be a copy of the old version in your packages folder (home/addons/packages) and you can do an install from zip then go to that file.

**Comment by kasekesy** [comment]
> > Does that mean it can’t be fixed? How do we install an older working version?
> 
> Unless you actively delete your kodi files there will be a copy of the old version in your packages folder (home/addons/packages) and you can do an install from zip then go to that file.

Well then I just screwed myself, 2 days ago I did a fresh reset and rejabreak because I thought that might have been the reason wasn’t working something was corrupted..... that sucks

**Comment by diemenz** [comment]
Previous versions are available on the GitHub. Download one and put it on a shared drive then install from zip where you saved it. I am rather certain that this will be fixed soon however as I tested Fens fix last night and it is fully working so venoms should be soon. 

Another reason why these developers are top notch!

**Comment by 123Venom** [comment]
> 
> 
> > > Does that mean it can’t be fixed? How do we install an older working version?
> > 
> > 
> > Unless you actively delete your kodi files there will be a copy of the old version in your packages folder (home/addons/packages) and you can do an install from zip then go to that file.
> 
> Well then I just screwed myself, 2 days ago I did a fresh reset and rejabreak because I thought that might have been the reason wasn’t working something was corrupted..... that sucks

don't waste to much time on this.  In speaking with Fen dev he's come up with a solution that believe you tested already in Fen and cured the problem, because both Fen and Venom are using the same new settings manager.  I'll dial in the changes and upload the fix for Apple devices soon.

**Comment by iAYMANi** [comment]
The latest version 4.15 works great on Apple TV

thank you very much
